# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ao5Mc06Bh1XuP3o8Q_sQC-YhBhHSK9JP
"""

!pip install streamlit requests

import streamlit as st
import requests

# Set page config
st.set_page_config(page_title="Weather App", page_icon="🌦️")

# Title and description
st.title("🌦️ Weather App")
st.markdown("Get real-time weather updates for any city worldwide!")

# Input field for city
city = st.text_input("Enter City Name")

# Replace this with your actual API key from OpenWeatherMap
api_key = "a29404cb347b8eea7ff23e874da148c7"

# Show weather details if city is entered
if city:
    url = f"http://api.openweathermap.org/data/2.5/weather?q={city}&appid={api_key}&units=metric"

    try:
        response = requests.get(url)
        data = response.json()

        if data["cod"] == 200:
            # Extract data
            city_name = data["name"]
            temp = data["main"]["temp"]
            desc = data["weather"][0]["description"].title()
            humidity = data["main"]["humidity"]
            wind = data["wind"]["speed"]

            # Display results
            st.subheader(f"📍 Weather in {city_name}")
            st.write(f"**🌡️ Temperature:** {temp} °C")
            st.write(f"**🌤️ Condition:** {desc}")
            st.write(f"**💧 Humidity:** {humidity}%")
            st.write(f"**🌬️ Wind Speed:** {wind} m/s")
        else:
            st.error("❌ City not found. Please try again.")

    except:
        st.error("⚠️ Error: Could not fetch data. Check your internet or API key.")

